<!DOCTYPE html>
<html lang="en" ng-app="myApp">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo $app_name; ?></title>

<link href="libs/uikit/css/uikit.almost-flat.min.css" rel="stylesheet">
<link href="css/datatables.uikit.min.css" rel="stylesheet">
<link href="css/app.css" rel="stylesheet">

<!-- js -->
<script src="js/jquery-1.12.4.min.js"></script>
<script src="js/jquery.dataTables.js"></script>
<script src="js/dataTables.uikit.js"></script>
<!-- angular -->
<script src="js/angular_1.5.2.min.js"></script>
<script src="js/angular-datatables.min.js"></script>
<script src="js/angular-ui-router.min.js"></script>
<script src="js/angular-cookies.min.js"></script>
<script src="js/angular-flash.js"></script>
<!-- app -->
<script src="js/main.js"></script>

<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->

</head>

<body>
	
	<nav class="uk-navbar uk-navbar-attached">
		<div class="uk-container uk-container-center">
			<a href="/" class="uk-navbar-brand"><?php echo $app_name; ?></a>
			<div class="uk-navbar-flip">
				<div class="uk-navbar-content" ng-show="currentUser.fullname">
					<i class="uk-icon-user"></i> {{currentUser.fullname}}
				</div>
			</div>
		</div>
	</nav>

	<div class="uk-container uk-container-center">

		<div class="uk-grid uk-grid-margin">

			<div class="uk-width-medium-1-5" ng-controller="SidebarCtrl" ng-show="currentUser.fullname">
				<div class="uk-panel uk-panel-box">
					<ul data-uk-nav="" class="uk-nav uk-nav-side uk-nav-parent-icon">
						<li class="uk-nav-header">Menu</li>
						<li class="uk-nav-divider"></li>
						<li ng-class="{'uk-active': isActive('/dashboard')}"><a ui-sref="dashboard"><i class="uk-icon-dashboard uk-icon-justify"></i> Dashboard</a></li>
						<li ng-class="{'uk-active': isActive('/users')}" ng-show="currentUser.groups.admin == 1" ><a ui-sref="users"><i class="uk-icon-users uk-icon-justify"></i> Users</a></li>
						<li><a ui-sref="logout"><i class="uk-icon-power-off uk-icon-justify"></i> Logout</a></li>
					</ul>
				</div>
				<flash:messages></flash:messages>
			</div>
			
			<div class="uk-width-medium-4-5">
				<div ui-view></div>
			</div>

		</div>

	</div>

</body>

</html>
